import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fast Delivery",
  description: "Generated by create next app",
};

import MainLayout from "./MainLayout";
import ServiceWorkerRegister from "./sw";
import PwaInstall from "./sw/PwaInstall";
import PushNotification from "./sw/PushNotification";
import Script from "next/script";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const gooogleAnalitycsId = "G-0G4ZD773X2";
  return (
    <html lang="es">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="theme-color" content="#ff7b00ff" />
        <link rel="icon" href="/icons/logo-192x192.png" />
        <link rel="apple-touch-icon" href="/icons/logo-192x192.png" />

        <Script
          async
          src={`https://www.googletagmanager.com/gtag/js?id=${gooogleAnalitycsId}`}
        />
        <Script
          id="google-analytics"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag() { dataLayer.push(arguments); }
              gtag('js', new Date());
              gtag('config', ${gooogleAnalitycsId});
            `,
          }}
        />
      </head>
      <body>
        <MainLayout>
          <ServiceWorkerRegister />
          {children}
        </MainLayout>
      </body>
    </html>
  );
}
