import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fast Delivery",
  description: "Generated by create next app",
};

import MainLayout from "./MainLayout";
import ServiceWorkerRegister from "./sw";
import PwaInstall from "./sw/PwaInstall";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="theme-color" content="#ff7b00ff" />
        <link rel="icon" href="/icons/logo-192x192.png" />
        <link rel="apple-touch-icon" href="/icons/logo-192x192.png" />
      </head>
      <body>
        <MainLayout>
          <ServiceWorkerRegister />
          <PwaInstall />
          {children}
        </MainLayout>
      </body>
    </html>
  );
}
